CREATE DATABASE PHP_APSL;

use PHP_APSL;

CREATE TABLE _User (
	_email VARCHAR(50) NOT NULL PRIMARY KEY,
	_password CHAR(32) NOT NULL
);

CREATE TABLE _UserHash (
	_email VARCHAR(50) NOT NULL,
	_hash CHAR(32) NOT NULL,
	_createdTime  DATETIME,
	FOREIGN KEY (_email) REFERENCES _User(_email) ON DELETE CASCADE
);